package com.ticketing.Model.enums;

public enum EventCategoryEnum {
    HOUSE_PARTY,
    WEDDING,
    HANGOUT,
    LAUNCH,
    MEETING,
    FAMILY,
    CULTURAL,
    SPORTS,
    TRAVEL,
    ENTERTAINMENT,
    LEISURE,
    HEALTH,
    RELIGIOUS,
    BUSINESS,
    ART,
    DEMO,
    MOVIE,
    COMPETITION,
    BOOKING,
    EXHIBITION,
    WORKSHOP,
    FESTIVAL,
    MUSICAL,
    WEBINAR,
    CONFERENCE,
    FOOD_AND_DRINK,
    SOCIAL_IMPACT,
    SCIENCE,
    TECHNOLOGY,
    BIRTHDAY,
    OTHER
}